Document: glyr
Title: Debian glyr Manual
Author: <insert document author here>
Abstract: This manual describes what glyr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glyr/glyr.sgml.gz

Format: postscript
Files: /usr/share/doc/glyr/glyr.ps.gz

Format: text
Files: /usr/share/doc/glyr/glyr.text.gz

Format: HTML
Index: /usr/share/doc/glyr/html/index.html
Files: /usr/share/doc/glyr/html/*.html
